name = "dag_json"
version = "2.0.0"
target = "javascript"
description = "Implementation of dag-json."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "dag_json" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 4.0.0"
multiformats = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
